name: Build & Test (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install 'cargo-all-features' helper
      run: cargo install cargo-all-features
    - name: Build with all combinations of feature flags
      run: cargo build-all-features --verbose
    - name: Test with all combinations of feature flags
      run: cargo test-all-features --verbose
