name: Source Control (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run rustfmt
      run: cargo fmt --check
    - name: Run clippy
      run: cargo clippy --all-features -- -D clippy::all